export enum ErrorCode {
  INVALID_INPUT = 'INVALID_INPUT',
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INFRASTRUCTURE_ERROR = 'INFRASTRUCTURE_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
