export enum ErrorCode {
  INVALID_INPUT = 'INVALID_INPUT',
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_AUTH_PROVIDER_CONFIGURATION = 'INVALID_AUTH_PROVIDER_CONFIGURATION',
  INVALID_REFRESH_TOKEN_EXPIRY = 'INVALID_REFRESH_TOKEN_EXPIRY',
  INVALID_REFRESH_TOKEN_REVOCATION = 'INVALID_REFRESH_TOKEN_REVOCATION',
  INVALID_POMODORO_DURATION = 'INVALID_POMODORO_DURATION',
  INVALID_FOCUS_SESSIONS_BEFORE_LONG_BREAK = 'INVALID_FOCUS_SESSIONS_BEFORE_LONG_BREAK',
  INVALID_POMODORO_HISTORY_DURATION = 'INVALID_POMODORO_HISTORY_DURATION',
  INVALID_POMODORO_HISTORY_RANGE = 'INVALID_POMODORO_HISTORY_RANGE',
  INVALID_PLAYLIST_POSITION = 'INVALID_PLAYLIST_POSITION',
  INVALID_PLAYLIST_ORDER = 'INVALID_PLAYLIST_ORDER',
  INVALID_MEDIA_DURATION = 'INVALID_MEDIA_DURATION',
  DATABASE_INITIALIZATION_FAILED = 'DATABASE_INITIALIZATION_FAILED',
  DATABASE_ADMIN_CONNECTION_CLOSE_FAILED = 'DATABASE_ADMIN_CONNECTION_CLOSE_FAILED',
  DATABASE_CONNECTION_FAILED = 'DATABASE_CONNECTION_FAILED',
  DATABASE_NOT_READY = 'DATABASE_NOT_READY',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export type InfrastructureErrorCode =
  | ErrorCode.DATABASE_INITIALIZATION_FAILED
  | ErrorCode.DATABASE_ADMIN_CONNECTION_CLOSE_FAILED
  | ErrorCode.DATABASE_CONNECTION_FAILED
  | ErrorCode.DATABASE_NOT_READY;
