import { HttpStatus } from '@nestjs/common';
import { ErrorCode } from '../exceptions/error-code.enum.js';

export const ERROR_STATUS = {
  [ErrorCode.INVALID_INPUT]: HttpStatus.BAD_REQUEST,
  [ErrorCode.BUSINESS_RULE_VIOLATION]: HttpStatus.UNPROCESSABLE_ENTITY,
  [ErrorCode.RESOURCE_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ErrorCode.CONFLICT]: HttpStatus.CONFLICT,
  [ErrorCode.UNAUTHORIZED]: HttpStatus.UNAUTHORIZED,
  [ErrorCode.FORBIDDEN]: HttpStatus.FORBIDDEN,
  [ErrorCode.EMAIL_ALREADY_REGISTERED]: HttpStatus.CONFLICT,
  [ErrorCode.INVALID_CREDENTIALS]: HttpStatus.UNAUTHORIZED,
  [ErrorCode.INVALID_REFRESH_TOKEN]: HttpStatus.UNAUTHORIZED,
  [ErrorCode.POMODORO_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ErrorCode.INVALID_AUTH_PROVIDER_CONFIGURATION]:
    HttpStatus.UNPROCESSABLE_ENTITY,
  [ErrorCode.INVALID_REFRESH_TOKEN_EXPIRY]: HttpStatus.UNPROCESSABLE_ENTITY,
  [ErrorCode.INVALID_REFRESH_TOKEN_REVOCATION]: HttpStatus.UNPROCESSABLE_ENTITY,
  [ErrorCode.INVALID_POMODORO_DURATION]: HttpStatus.UNPROCESSABLE_ENTITY,
  [ErrorCode.INVALID_FOCUS_SESSIONS_BEFORE_LONG_BREAK]:
    HttpStatus.UNPROCESSABLE_ENTITY,
  [ErrorCode.INVALID_POMODORO_HISTORY_DURATION]:
    HttpStatus.UNPROCESSABLE_ENTITY,
  [ErrorCode.INVALID_POMODORO_HISTORY_RANGE]: HttpStatus.UNPROCESSABLE_ENTITY,
  [ErrorCode.INVALID_PLAYLIST_POSITION]: HttpStatus.UNPROCESSABLE_ENTITY,
  [ErrorCode.INVALID_PLAYLIST_ORDER]: HttpStatus.UNPROCESSABLE_ENTITY,
  [ErrorCode.INVALID_MEDIA_DURATION]: HttpStatus.UNPROCESSABLE_ENTITY,
  [ErrorCode.DATABASE_INITIALIZATION_FAILED]: HttpStatus.SERVICE_UNAVAILABLE,
  [ErrorCode.DATABASE_ADMIN_CONNECTION_CLOSE_FAILED]:
    HttpStatus.SERVICE_UNAVAILABLE,
  [ErrorCode.DATABASE_CONNECTION_FAILED]: HttpStatus.SERVICE_UNAVAILABLE,
  [ErrorCode.DATABASE_NOT_READY]: HttpStatus.SERVICE_UNAVAILABLE,
  [ErrorCode.INTERNAL_ERROR]: HttpStatus.INTERNAL_SERVER_ERROR,
} as const satisfies Record<ErrorCode, HttpStatus>;
